AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Infrastructure for E-Ledger Blockchain Supply Chain App'

Parameters:
  ProjectName:
    Type: String
    Default: e-ledger-blockchain
  Environment:
    Type: String
    Default: production
    AllowedValues: [production, staging, development]

Resources:
  # S3 Bucket for Static Website Hosting
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-web-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: 'AWS::CloudFront::OriginAccessControl'
    Properties:
      OriginAccessControlConfig:
        Description: !Sub 'OAC for ${ProjectName}'
        Name: !Sub '${ProjectName}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # S3 Bucket Policy to allow CloudFront access
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}'

  # CloudFront Distribution
  WebsiteDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

  # DynamoDB Table for Blockchain Ledger Data
  LedgerTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${ProjectName}-ledger'
      AttributeDefinitions:
        - AttributeName: batchID
          AttributeType: S
        - AttributeName: manufacturerGLN
          AttributeType: S
      KeySchema:
        - AttributeName: batchID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ManufacturerIndex
          KeySchema:
            - AttributeName: manufacturerGLN
              KeyType: HASH
            - AttributeName: batchID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteDistribution.DomainName
    Description: 'CloudFront URL for the E-Ledger Application'
  S3Bucket:
    Value: !Ref WebsiteBucket
    Description: 'Deployment Bucket'
